### ISSUE TITLE
Ban user

### ISSUE THREAD

**Issue by gitiray** [ArchivedCodes/FileStreamBot#4]
hello i saw you asked for ban user in another repo
does your version support this feature?

**Comment by DeekshithSH** [comment]
github.com/DeekshithSH/FileStreamBot has Ban feature
I am planning to Update that repo to Support Pyrogram V2

**Comment by gitiray** [comment]
thanks man but there has only a var `BANNED_CHANNELS`
i need to ban user instead of ban channel

**Comment by DeekshithSH** [comment]
@gitiray Use /ban <user id>
Command

**Comment by DeekshithSH** [comment]
The Repo has been Updated you can use the Following command
`/ban <user_id>` to Ban a User
