### ISSUE TITLE
Channel download is not fixed

### ISSUE THREAD

**Issue by ramanveerji** [ArchivedCodes/FileStreamBot#6]
The ON_HEROKU var is causing issue, also channel link generated has no hash. It needs to be fixed.

**Comment by DeekshithSH** [comment]
@ramanveerji I forgot that the bot support channel also 😅.
Will fix it tomorrow.

**Comment by ramanveerji** [comment]
> @ramanveerji I forgot that the bot support channel also 😅.
> Will fix it tomorrow.

I think you forgot. Just a reminder. Please fix it.

**Comment by DeekshithSH** [comment]
Fixed the issue

**Comment by ramanveerji** [comment]
> Fixed the issue

I tried to deploy. But now it is showing error. And bot is not deploying.
This is the error 
ERROR - cannot import name 'get_file_info' from 'WebStreamer.utils.file_properties' (/workspace/WebStreamer/utils/file_properties.py)

**Comment by DeekshithSH** [comment]
> > Fixed the issue
> 
> I tried to deploy. But now it is showing error. And bot is not deploying. This is the error ERROR - cannot import name 'get_file_info' from 'WebStreamer.utils.file_properties' (/workspace/WebStreamer/utils/file_properties.py)

I tested it and at that time it's working
I will check it tomorrow

**Comment by ramanveerji** [comment]
> > > Fixed the issue
> > 
> > 
> > I tried to deploy. But now it is showing error. And bot is not deploying. This is the error ERROR - cannot import name 'get_file_info' from 'WebStreamer.utils.file_properties' (/workspace/WebStreamer/utils/file_properties.py)
> 
> I tested it and at that time it's working I will check it tomorrow

ok

**Comment by DeekshithSH** [comment]
Did you used git clone to clone the repository or git pull to fetch the changes
Or Directly copy pasted the code of stream.py?

**Comment by ramanveerji** [comment]
> Did you used git clone to clone the repository or git pull to fetch the changes
> Or Directly copy pasted the code of stream.py?

Gitclone

**Comment by DeekshithSH** [comment]
@ramanveerji Try deleting and clone the repository again

**Comment by ramanveerji** [comment]
> @ramanveerji Try deleting and clone the repository again

I will try and report soon

**Comment by ramanveerji** [comment]
@DeekshithSH The bot got deployed, but I am getting the following error when I try to send a file in a private channel. The bot is having all admin rights 
Telegram says: [400 MESSAGE_ID_INVALID] - The message id is invalid (caused by "messages.EditMessage")

**Comment by DeekshithSH** [comment]
@ramanveerji Forwarded the File?

**Comment by ramanveerji** [comment]
> @ramanveerji Forwarded the File?

Yes. It doesn't support forwarding?

**Comment by DeekshithSH** [comment]
@ramanveerji Bot can't edit forwarded messages

**Comment by ramanveerji** [comment]
> > @ramanveerji Forwarded the File?
> 
> Yes. It doesn't support forwarding?

Actually, I was using some other repo, I do not know, it was old, and in it, forwarding was working and bot can give the links as well.

**Comment by ramanveerji** [comment]
I tried forwarding files without the tag, It should work. Kindly check.

**Comment by DeekshithSH** [comment]
> > @ramanveerji Forwarded the File?
> 
> Yes. It doesn't support forwarding?

When forwarding chose "Hide Sender Name"

**Comment by ramanveerji** [comment]
> 

Yes, I did that only, still nothing happens.

**Comment by ramanveerji** [comment]
Or maybe some files aren't supported. I tried forwarding a song, maybe I must try other file types also.

**Comment by ramanveerji** [comment]
Audio files aren't supported. Videos, zips, apks, pdfs are working fine.

**Comment by DeekshithSH** [comment]
> Or maybe some files aren't supported. I tried forwarding a song, maybe I must try other file types also.

Yes the current code only generate link for Document and Video

**Comment by ramanveerji** [comment]
> 

Understood, anyway I got to know something new..

**Comment by DeekshithSH** [comment]
> > > @ramanveerji Forwarded the File?
> > 
> > 
> > Yes. It doesn't support forwarding?
> 
> Actually, I was using some other repo, I do not know, it was old, and in it, forwarding was working and bot can give the links as well.

Some bots delete the forwarded message and send it again without forward tag to add Download Button
